BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Category" (
	"CategoryID"	INTEGER NOT NULL UNIQUE,
	"CategoryName"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("CategoryID")
);
CREATE TABLE IF NOT EXISTS "Customer" (
	"CustomerID"	INTEGER NOT NULL UNIQUE,
	"FirstName"	TEXT NOT NULL,
	"LastName"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	PRIMARY KEY("CustomerID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Order" (
	"OrderID"	INTEGER NOT NULL UNIQUE,
	"OrderDate"	INTEGER NOT NULL,
	"TotalAmount"	REAL NOT NULL,
	"CustomerID"	INTEGER,
	FOREIGN KEY("CustomerID") REFERENCES "Customer"("CustomerID"),
	PRIMARY KEY("OrderID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Product" (
	"ProductID"	INTEGER NOT NULL UNIQUE,
	"ProductName"	TEXT NOT NULL UNIQUE,
	"CategoryID"	INTEGER,
	"StockQuantity"	INTEGER NOT NULL,
	FOREIGN KEY("CategoryID") REFERENCES "Category"("CategoryID"),
	PRIMARY KEY("ProductID" AUTOINCREMENT)
);
COMMIT;
